[package]
name = "mmtk_ruby"
version = "0.1.0"
authors = [
    "Kunshan Wang <wks1986@gmail.com>",
    "Angus Atkinson <4848802+angussidney@users.noreply.github.com>",
    ]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "mmtk_ruby"
# be careful - Link-Time Optimisation (LTO) is only allowed for certain crate types
crate-type = ["cdylib", "staticlib"]

[profile.release]
lto = true

[dependencies]
# Definitions for interoperating with C code on the ruby side
libc = "0.2"
lazy_static = "1.1"
log = "0.4.14"
env_logger = "0.9.0"
memoffset = { version = "0.6.5", features = ["unstable_const"] }

# Uncomment this to use mmtk-core from the official repository.
mmtk = { git = "https://github.com/wks/mmtk-core.git", branch = "is_arbitrary_address_alloced", features = ["is_mmtk_object"]}

# Uncomment this to use mmtk-core from a local repository.
#mmtk = { path = "../../mmtk-core", features = ["is_mmtk_object"] }
